/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_janggi_GameActivity_GameBoard_interrupt_thread */

#ifndef _Included_com_example_janggi_GameActivity_GameBoard_interrupt_thread
#define _Included_com_example_janggi_GameActivity_GameBoard_interrupt_thread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_janggi_GameActivity_GameBoard_interrupt_thread_MIN_PRIORITY
#define com_example_janggi_GameActivity_GameBoard_interrupt_thread_MIN_PRIORITY 1L
#undef com_example_janggi_GameActivity_GameBoard_interrupt_thread_NORM_PRIORITY
#define com_example_janggi_GameActivity_GameBoard_interrupt_thread_NORM_PRIORITY 5L
#undef com_example_janggi_GameActivity_GameBoard_interrupt_thread_MAX_PRIORITY
#define com_example_janggi_GameActivity_GameBoard_interrupt_thread_MAX_PRIORITY 10L
/*
 * Class:     com_example_janggi_GameActivity_GameBoard_interrupt_thread
 * Method:    sense_interrupt
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_janggi_GameActivity_00024GameBoard_00024interrupt_1thread_sense_1interrupt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
