/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_janggi_GameActivity_GameBoard */

#ifndef _Included_com_example_janggi_GameActivity_GameBoard
#define _Included_com_example_janggi_GameActivity_GameBoard
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_janggi_GameActivity_GameBoard_row
#define com_example_janggi_GameActivity_GameBoard_row 10L
#undef com_example_janggi_GameActivity_GameBoard_col
#define com_example_janggi_GameActivity_GameBoard_col 9L
#undef com_example_janggi_GameActivity_GameBoard_RED
#define com_example_janggi_GameActivity_GameBoard_RED 1L
#undef com_example_janggi_GameActivity_GameBoard_BLUE
#define com_example_janggi_GameActivity_GameBoard_BLUE 0L
/*
 * Class:     com_example_janggi_GameActivity_GameBoard
 * Method:    Poss_pos
 * Signature: (II[[I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_janggi_GameActivity_00024GameBoard_Poss_1pos
  (JNIEnv *, jobject, jint, jint, jobjectArray);

/*
 * Class:     com_example_janggi_GameActivity_GameBoard
 * Method:    timer_start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_janggi_GameActivity_00024GameBoard_timer_1start
  (JNIEnv *, jobject);

/*
 * Class:     com_example_janggi_GameActivity_GameBoard
 * Method:    timer_turn_change
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_janggi_GameActivity_00024GameBoard_timer_1turn_1change
  (JNIEnv *, jobject);

/*
 * Class:     com_example_janggi_GameActivity_GameBoard
 * Method:    timer_end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_janggi_GameActivity_00024GameBoard_timer_1end
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
